function stimTable = s_OptfMRI_ER_ExtendTable(stimTable,ExpParaSets)
% Extend a stimTable that has been generated by reshaping a stimList.
% Appending new columns and re-format table into the standrad template.
% 
% Input:
%   Positional Arguments (Required):
%       stimTable - an incomplete stimTable, which only has stimType and 
%                   stimOnset columns.
%       ExpParaSets - a struct contains basic information about experiment
%                       parameter settings, see details in 
%                                           's_OptfMRI_ER_ReshapeList'.
% Output:
%   stimTable - an extended stimuli table.
% 
% Written By Kunru Song 2023.11.21


% Get Trial No.
stimTable.TrialNo = (1:height(stimTable))';
% Get Inter-Stimulus Intervals
% The first trial should directly use the onset time of stimulus, because
% there is no more trials before it.
stimTable.ISI = [...
    stimTable.stimOnset(1)  - ExpParaSets.StimDura;...
    diff(stimTable.stimOnset)...
    ];

% Manually Changeing to reduce scanning length, which is useful to insert
% some empty durations at the beginning and the end of experiment
stimTable.ISI(stimTable.ISI == uint32(3000)) = 2500;
stimTable.ISI(stimTable.ISI == uint32(6000)) = 3500;
stimTable.stimOnset = cumsum(stimTable.ISI);


stimTable.stimOffset = stimTable.stimOnset + ExpParaSets.StimDura;
stimTable.TrialStart =  stimTable.stimOnset - stimTable.ISI + (ExpParaSets.StimDura + ExpParaSets.ResponseWindow);
stimTable.TrialStart(1) = 0;
stimTable.TrialEnd = stimTable.stimOffset + ExpParaSets.ResponseWindow;

stimTable.JitterDura = stimTable.stimOnset - stimTable.TrialStart;
stimTable.TrialDura = stimTable.TrialEnd - stimTable.TrialStart;

stimTable = movevars(stimTable,'TrialNo','Before',1);
stimTable = movevars(stimTable,'stimType','After','TrialNo');
stimTable = movevars(stimTable,'ISI','After','stimType');
stimTable = movevars(stimTable,'TrialStart','After','ISI');
stimTable = movevars(stimTable,'JitterDura','After','TrialStart');
stimTable = movevars(stimTable,'stimOnset','After','JitterDura');
stimTable = movevars(stimTable,'stimOffset','After','stimOnset');
stimTable = movevars(stimTable,'TrialEnd','After','stimOffset');
stimTable = movevars(stimTable,'TrialDura','After','TrialEnd');
